### ISSUE TITLE
Add way to get a random image from a shared gallery

### ISSUE THREAD

**Issue by roachcord3** [floogulinc/hyshare#300]
I'd like for there to be a way to get a random image from a gallery via a static path. It would be fine it it serves it as a 302 redirect to a `/view/` path, or if the path just serves up a random file from the gallery each time, either works for me.

My use case: I'm using a Windows program called [Dual Monitor Tools](https://dualmonitortool.sourceforge.net/dmt_wallpaperchanger.html) that lets you source wallpaper from, among other things, web locations. However, it only seems to support web locations that serve the files themselves, so anything that serves an index/gallery type page won't work. The alternative (besides writing my own server to do this) would be to export the files to somewhere as an SMB mount. That's inconvenient for just a single-user tailnet; forget about a hypothetical multi-user tailnet!

![Screenshot of URL provider dialog window from Dual Monitor Tools](https://github.com/floogulinc/hyshare/assets/73802796/84afe19a-7e88-4d5c-ac40-6c22dc8e9b46)

**Comment by floogulinc** [comment]
Added in https://github.com/floogulinc/hyshare/releases/tag/v0.16.0. use `/gallery/{tag}/random/file` for a redirect to the a random raw file from the gallery.
